---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/calico-felix --version
      register: felix_test_output
    - debug:
        msg: '{{ felix_test_output.stdout }}'
