---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ felix_url }} to {{ felix_install_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ felix_url }}'
    dest: '{{ felix_install_exe }}'
    checksum: '{{ felix_checksum }}'
    mode: '755'
- name: Linking {{ felix_link }} to {{ felix_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ felix_install_exe }}'
    dest: '{{ felix_link }}'
    state: link
